import Spell from "@/controllers/Spell"

export default {
  'Alarte Ascendare': new Spell(1, 'Alarte Ascendare', 1, 2, Spell.TYPE_MIXED, 5, 2, 'Combat Spell. If target model doesn\'t have the Fly rule, it suffers 2 Damage.'),
  'Apparition': new Spell(3, 'Apparition', 4, 3, Spell.TYPE_MIXED, null, 2, 'Immediately move the model up to 8 spaces, ignoring obstacles, and treating Difficult and Impassable terrain as Open Terrain.'),
  'Avada Kedavra': new Spell(5, 'Avada Kedavra', 2, 4, Spell.TYPE_DARK, 4, 3, 'Combat Spell. If successful, target model is removed from play, ignoring all normal Damage rules.', false, 0, 'unforgivable'),
  'Bombarda': new Spell(1000, 'Bombarda', 1, 2, Spell.TYPE_MIXED, 4, 2, 'Combat Spell. If successful, target model suffers 2 Physical Damage.'),
  'Bombarda Maxima': new Spell(3, 'Bombarda Maxima', 2, 3, Spell.TYPE_MIXED, 4, 3, 'Combat Spell. If successful, target model and all models within 2 Spaces of it (friend or foe) suffer 3 Physical Damage.'),
  'Confringo': new Spell(2, 'Confringo', 1, 3, Spell.TYPE_DARK, 4, 2, 'Combat Spell. If successful, target model suffers 2 Physical Damage with the Burning Effect.'),
  'Confundo': new Spell(1, 'Confundo', 0, 1, Spell.TYPE_MIXED, 4, 2, 'Combat Spell. If successful, target model loses 1 Action in its next activation (the opponent chooses which Action).'),
  'Counter-Spell': new Spell(3, 'Counter-Spell', '?', 3, Spell.TYPE_MIXED, 4, 3, 'Reaction: Model within range casts Spell. Difficulty is equal to the number of Power points used to cast trigger spell, +1. If successful, trigger spell automatically fails.'),
  'Crucio': new Spell(3, 'Crucio', 1, 3, Spell.TYPE_DARK, 4, 2, 'Combat Spell. If successful, target model suffers 2 Magical Damage', true, 1, 'unforgivable'),
  'Episkey': new Spell(2, 'Episkey', 4, 3, Spell.TYPE_LIGHT, 4, 2, 'Target model heals up to 2 Damage levels.'),
  'Evanesco': new Spell(1000, 'Evanesco', 5, 3, Spell.TYPE_MIXED, 4, 3, 'Remove target scenery overlay from the board.'),
  'Expecto Patronum': new Spell(3,'Expecto Patronum', 4, 3, Spell.TYPE_LIGHT, 3, 3, 'Place a Patronus marker within range.', true, 2),
  'Expelliarmus': new Spell(1, 'Expelliarmus', 0, 1, Spell.TYPE_MIXED, 4, 1, 'Combat Spell. If successful, choose one of the target\'s Item cards. That card may not be used for the rest of the round.'),
  'Finite Incantatem': new Spell(2, 'Finite Incantatem', 4, 2, Spell.TYPE_MIXED, 4, 2, 'Removes all Effects produced by spells from target model. Any spells with Upkeeps targeting the model are immediately ended.'),
  'Impedimenta': new Spell(2, 'Impedimenta', 4, 1, Spell.TYPE_MIXED, 4, 2, 'Target model can\'t perform Move Actions in its next activation'),
  'Jelly-Legs Jinx': new Spell(1000, 'Jelly-Legs Jinx', 3, 2, Spell.TYPE_MIXED, 4, 2, 'Target model receives the Slow/3 effect.'),
  'Obliviate': new Spell(1, 'Obliviate', 3, 1, Spell.TYPE_MIXED, 4, 1, 'Target model increases the Difficulty of the next Challenge it is involved in by 2.'),
  'Petrificus Totalus': new Spell(2,'Petrificus Totalus', 1, 2, Spell.TYPE_MIXED, 4, 2, 'Combat Spell. Target model suffers the Petrify Effect'),
  'Protego': new Spell(2, 'Protego', 4, 2, Spell.TYPE_MIXED, 4, 2, 'Target model gains 1 automatic Success on all Defense rolls until the end of the round.', true, 2),
  'Protego Maxima': new Spell(3, 'Protego Maxima', 5, 3, Spell.TYPE_MIXED, 4, 2, 'Target model gains 2 automatic Successes on all Defense rolls until the end of the round.', true, 2),
  'Reducto': new Spell(1000,'Reducto', 5, 3, Spell.TYPE_MIXED, 3, 3, 'Remove target Impassable terrain overlay'),
  'Sectumsempra': new Spell(1000, 'Sectumsempra', 1, 3, Spell.TYPE_DARK, 4, 2, 'Combat Spell. Target model suffers 1 Physical Damage, and cannot perform Move Actions in its next activation.', true, 2),
  'Silencio': new Spell(1, 'Silencio', 0, 1, Spell.TYPE_MIXED, 4, 1, 'Combat Spell. Target model cannot perform the Cast Spell Action in its next activation.'),
  'Stupefy': new Spell(1, 'Stupefy', 0, 1, Spell.TYPE_MIXED, 4, 1, 'Combat Spell. Target model suffers 1 Physical Damage.'),
  'Wingardium Leviosa': new Spell(1, 'Wingardium Leviosa', 3, 1, Spell.TYPE_MIXED, 4, 1, 'Choose any marker that was placed by a Quest card. Move target marker up to 3 spaces.'),
}
